import * as stylex from '@stylexjs/stylex'
import { color, font, radius, size, space } from '../../tokens.stylex'

/** Shared building blocks for the settings tabs. */
export const s = stylex.create({
  stack: { display: 'flex', flexDirection: 'column', gap: space.md, width: '100%' },
  section: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: space.sm,
    paddingInline: space.lg,
    paddingTop: space.xl,
  },
  h3: { display: 'block', margin: 0, fontSize: font.sm, fontWeight: 600 },
  hint: { margin: 0, color: color.muted, lineHeight: 1.45 },
  /** a quiet info box for limitations shown upfront */
  limit: {
    display: 'flex',
    gap: space.sm,
    margin: 0,
    padding: space.sm,
    borderRadius: radius.sm,
    backgroundColor: color.sunken,
    color: color.ink,
    lineHeight: 1.45,
  },
  buttons: { display: 'flex', flexWrap: 'wrap', gap: space.sm },
  fileBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: space.sm,
    height: { default: size.control, '@media (pointer: coarse)': size.tap },
    paddingInline: space.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: color.line,
    backgroundColor: { default: color.surface, ':hover': color.sunken },
    fontWeight: 500,
    cursor: 'pointer',
    ':focus-within': { outline: `2px solid ${color.focus}`, outlineOffset: '2px' },
  },
  list: { listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: space.sm, width: '100%' },
  item: {
    display: 'flex',
    flexDirection: 'column',
    gap: space.sm,
    padding: space.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: color.line,
  },
  itemHead: { display: 'flex', alignItems: 'flex-start', gap: space.sm },
  itemMain: { display: 'flex', gap: space.sm, flex: 1, minWidth: 0, cursor: 'pointer' },
  itemText: { display: 'flex', flexDirection: 'column', gap: space.xxs, minWidth: 0 },
  itemActions: { display: 'flex', flexShrink: 0 },
  name: { display: 'flex', alignItems: 'center', gap: space.sm, fontWeight: 600 },
  row: { display: 'flex', alignItems: 'flex-start', gap: space.sm, lineHeight: 1.45, cursor: 'pointer' },
  field: { display: 'flex', flexDirection: 'column', gap: space.xs, color: color.ink, width: '100%' },
  input: {
    height: { default: size.control, '@media (pointer: coarse)': size.tap },
    width: '100%',
    minWidth: 0,
    paddingInline: space.sm,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: color.line,
    backgroundColor: color.bg,
  },
  short: { width: size.field },
  mono: { fontFamily: font.mono, fontSize: font.xs },
  textarea: {
    width: '100%',
    resize: 'vertical',
    padding: space.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: color.line,
    backgroundColor: color.bg,
    lineHeight: 1.5,
  },
  ok: { margin: 0, color: color.signal },
  err: { display: 'flex', gap: space.xs, margin: 0, color: color.danger },
  warn: { color: color.warn },
  meta: { fontSize: font.xs, color: color.muted },
})
